name: flutter_tdd_structure
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_app_navigator: ^1.0.1
  app_color: ^0.0.7
  flutter_androssy: ^0.2.8-alpha3
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true